
export const SIDEBARTOGGLE = 'SIDEBARTOGGLE'
export const SIDEBARUSER = 'SIDEBARUSER'


export const SIGNUPTOGGLE = 'SIGNUPTOGGLE'
export const SIGNUPSTEPS = 'SIGNUPSTEPS'
export const SIGNUPTYPE = 'SIGNUPTYPE'
export const CLEARSIGNUP = 'CLEARSIGNUP'


export const VERIFYDATA = 'VERIFYDATA'
export const VERIFYDETAILSVALUE = 'VERIFYDETAILSVALUE'
export const SIGNUPDATA = 'SINGUPDATA'
export const CLEARSIGNUPDATA = 'CLEARSIGNUPDATA'