
export const SIDEBARTOGGLE = 'SIDEBARTOGGLE'
export const SIDEBARUSER = 'SIDEBARUSER'
export const USERNAME = 'USERNAME'


export const SIGNUPTOGGLE = 'SIGNUPTOGGLE'
export const SIGNUPSTEPS = 'SIGNUPSTEPS'
export const SIGNUPTYPE = 'SIGNUPTYPE'
export const CLEARSIGNUP = 'CLEARSIGNUP'


export const VERIFYDATA = 'VERIFYDATA'
export const VERIFYDETAILSVALUE = 'VERIFYDETAILSVALUE'
export const VERIFIED = 'VERIFIED'
export const SIGNUPDATA = 'SINGUPDATA'
export const SIGNUPEMAIL = 'SINGUPEMAIL'
export const CLEARSIGNUPDATA = 'CLEARSIGNUPDATA'


export const ATTENDANCETYPE = 'ATTENDANCETYPE'
export const DAYATTENDANCE = 'DAYATTENDANCE'
export const PUSHSTUDENT = 'PUSHSTUDENT'

export const TEACHERSLECTURES = 'TEACHERSLECTURES'
export const ADDATTENDANCE = 'ADDATTENDANCE'
export const EDITATTENDANCE = 'EDITATTENDANCE'