
export const SIDEBARTOGGLE = 'SIDEBARTOGGLE'
export const SIDEBARUSER = 'SIDEBARUSER'
export const USERNAME = 'USERNAME'


export const SIGNUPTOGGLE = 'SIGNUPTOGGLE'
export const SIGNUPSTEPS = 'SIGNUPSTEPS'
export const SIGNUPTYPE = 'SIGNUPTYPE'
export const CLEARSIGNUP = 'CLEARSIGNUP'


export const VERIFYDATA = 'VERIFYDATA'
export const VERIFYDETAILSVALUE = 'VERIFYDETAILSVALUE'
export const VERIFIED = 'VERIFIED'
export const SIGNUPDATA = 'SINGUPDATA'
export const SIGNUPEMAIL = 'SINGUPEMAIL'
export const CLEARSIGNUPDATA = 'CLEARSIGNUPDATA'


export const ATTENDANCETYPE = 'ATTENDANCETYPE'
export const DAYATTENDANCE = 'DAYATTENDANCE'
export const PUSHSTUDENT = 'PUSHSTUDENT'

export const TEACHERSLECTURES = 'TEACHERSLECTURES'
export const ADDATTENDANCE = 'ADDATTENDANCE'
export const EDITATTENDANCE = 'EDITATTENDANCE'
export const ATTENDANCEDATE = 'ATTENDANCEDATE'
export const GET_lECTURES_BEGIN = 'GET_lECTURES_BEGIN'
export const SET_SINGLE_LECTURE = 'SET_SINGLE_LECTURE'
export const GET_lECTURES_SUCCESS = 'GET_lECTURES_SUCCESS'
export const GET_PRLABS_SUCCESS = 'GET_PRLABS_SUCCESS'
export const GET_lECTURES_ERROR = 'GET_lECTURES_ERROR'

export const SET_ALL_NOTICES = 'SET_ALL_NOTICES'
export const SET_ACTIVE_NOTICE = 'SET_ACTIVE_NOTICE'
export const SET_ACTIVE_NOTICE_DATAS = 'SET_ACTIVE_NOTICE_DATAS'

export const SET_ALL_BATCHES = 'SET_ALL_BATCHES'

export const SET_ALL_DEPARTMENTS = 'SET_ALL_DEPARTMENTS'

export const SET_ALL_PROGRAMS = 'SET_ALL_PROGRAMS'

export const SET_ALL_CLASSES = 'SET_ALL_CLASSES'

export const SET_USER_DETAILS = 'SET_USER_DETAILS'