# Generated by Django 4.1.5 on 2023-01-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
