# Generated by Django 4.1.5 on 2023-01-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0002_batch_class_department_parent_student_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identificationDocumentNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identificationDocumentType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='temporaryAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
