# Generated by Django 4.1.5 on 2023-01-13 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0002_userprofile_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='parentOf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Student_Parent_relation', to='wrcms.student'),
        ),
    ]
