# Generated by Django 4.1.5 on 2023-01-11 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wrcms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wrcms', '0003_userprofile_identificationdocumentnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='date_added',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='date_added',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_added',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_added',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_added',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portalId',
            field=models.PositiveIntegerField(default=wrcms.models.create_portalId, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
