# Generated by Django 4.1.5 on 2023-01-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0006_student_isparentregistered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='identificationDocumentType',
            field=models.CharField(blank=True, choices=[('Citizenship', 'Citizenship'), ('Passport', 'Passport')], max_length=255, null=True),
        ),
    ]
