# Generated by Django 4.1.5 on 2023-02-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0009_student_rollnumber_userprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='syllabus/')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Program_belongs_to_department', to='wrcms.department')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=1024)),
                ('subjectCode', models.CharField(blank=True, max_length=12, null=True)),
                ('subjectType', models.CharField(blank=True, choices=[('Theory', 'Theory'), ('Practical', 'Practical')], max_length=10, null=True)),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('fullMarks', models.IntegerField(blank=True, null=True)),
                ('passMarks', models.IntegerField(blank=True, null=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wrcms.program')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isArchived', models.BooleanField(default=False)),
                ('totalLectureDays', models.IntegerField(default=0)),
                ('cLass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent')], max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('cLass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.class')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.student')),
            ],
        ),
    ]
