# Generated by Django 4.1.5 on 2023-02-08 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0010_program_subject_lecture_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrcms.batch'),
        ),
        migrations.AlterField(
            model_name='class',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrcms.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parentOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Student_Parent_relation', to='wrcms.student'),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Program_belongs_to_department', to='wrcms.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrcms.batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='cLass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrcms.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrcms.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollNumber',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wrcms.program'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrcms.department'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.CharField(default='2057/09/25', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firstName',
            field=models.CharField(default='Hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='identificationDocumentNumber',
            field=models.CharField(default='XX-XX-XX-XXXXX', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='identificationDocumentType',
            field=models.CharField(blank=True, choices=[('Citizenship', 'Citizenship'), ('Passport', 'Passport')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(default='Hello', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrole',
            name='type',
            field=models.CharField(default='Student', max_length=255),
            preserve_default=False,
        ),
    ]
