# Generated by Django 4.1.5 on 2023-02-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0011_alter_class_batch_alter_class_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
