# Generated by Django 4.1.5 on 2023-02-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0012_alter_subject_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
