# Generated by Django 4.1.5 on 2023-02-17 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0013_lecture_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PracticalClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=1)),
                ('isArchived', models.BooleanField(default=False)),
                ('totalLabDays', models.IntegerField(default=0)),
                ('cLass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.subject')),
                ('teacherOne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Teacher_One', to='wrcms.teacher')),
                ('teacherTwo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Teacher_Two', to='wrcms.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='PracticalAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('cLass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.class')),
                ('practicalClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.practicalclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.student')),
            ],
        ),
    ]
