# Generated by Django 4.1.5 on 2023-03-01 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wrcms', '0014_alter_attendance_status_practicalclass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classRepresentative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Class_Representative', to='wrcms.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='viceClassRepresentative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Vice_Class_Representative', to='wrcms.student'),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('noticeType', models.CharField(blank=True, choices=[('Class', 'Class'), ('Department', 'Department'), ('College', 'College')], max_length=10, null=True)),
                ('noticeFor', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
