# Generated by Django 4.1.5 on 2023-03-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0015_alter_class_classrepresentative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='deputyHeadOfDepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Deputy_Head_of_Department', to='wrcms.teacher'),
        ),
        migrations.AlterField(
            model_name='department',
            name='headOfDepartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Head_of_Department', to='wrcms.teacher'),
        ),
    ]
