# Generated by Django 4.1.5 on 2023-05-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0017_notice_postedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='postedOn',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
