# Generated by Django 4.1.5 on 2023-05-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0018_alter_notice_postedon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routineType', models.CharField(blank=True, choices=[('ClassRoutine', 'ClassRoutine'), ('TeacherRoutine', 'TeacherRoutine')], max_length=14, null=True)),
                ('routineFor', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('routineImage', models.ImageField(blank=True, null=True, upload_to='routines/')),
                ('information', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
