# Generated by Django 4.1.5 on 2023-05-07 06:31

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0019_routine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='routineImage',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='routines/'),
        ),
    ]
