# Generated by Django 4.1.5 on 2023-05-07 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0020_alter_routine_routineimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrcms.program'),
        ),
    ]
