# Generated by Django 4.1.5 on 2023-05-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0022_rename_subjectcode_subject_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='graduated',
            field=models.BooleanField(default=False),
        ),
    ]
