# Generated by Django 4.1.5 on 2023-05-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0024_remove_class_graduated_batch_graduated'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
