# Generated by Django 4.1.5 on 2023-05-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0025_department_mail_alter_batch_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicalclass',
            name='cLass',
        ),
        migrations.RemoveField(
            model_name='practicalclass',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='practicalclass',
            name='teacherOne',
        ),
        migrations.RemoveField(
            model_name='practicalclass',
            name='teacherTwo',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=models.CharField(choices=[('Theory', 'Theory'), ('Practical', 'Practical')], default='Theory', max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PracticalAttendance',
        ),
        migrations.DeleteModel(
            name='PracticalClass',
        ),
    ]
