# Generated by Django 4.1.5 on 2023-05-16 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0026_remove_practicalclass_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrcms.teacher')),
            ],
        ),
    ]
