# Generated by Django 4.1.5 on 2023-05-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0027_teacheradvice'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_graduated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_working',
            field=models.BooleanField(default=True),
        ),
    ]
