# Generated by Django 4.1.5 on 2023-05-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0029_lecture_internalmarksadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='practicalAssessment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='practicalFinal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='theoryAssessment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='theoryFinal',
            field=models.IntegerField(default=0),
        ),
    ]
