# Generated by Django 4.1.5 on 2023-05-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrcms', '0030_alter_subject_practicalassessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='identificationDocumentNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
