# Generated by Django 4.1.5 on 2023-05-08 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wrcms', '0022_rename_subjectcode_subject_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=True)),
                ('leaveStartDate', models.CharField(max_length=255)),
                ('leaveEndDate', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('approvedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wrcms.teacher')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.lecture')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.student')),
            ],
        ),
    ]
