# Generated by Django 4.1.5 on 2023-05-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
