# Generated by Django 4.1.5 on 2023-05-20 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wrcms', '0029_lecture_internalmarksadded'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('theoryAssessment', models.IntegerField(blank=True, null=True)),
                ('practicalAssessment', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrcms.subject')),
            ],
        ),
    ]
