# Generated by Django 4.1.5 on 2023-05-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalmark',
            name='practicalAssessment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='internalmark',
            name='theoryAssessment',
            field=models.IntegerField(default=0),
        ),
    ]
